**Numpy:**

In [1]:
# Importanto o numpy :

import numpy as np

# Criar uma matriz unidimensional:

matriz = np.array([1,2,3,4,5,6])

print(matriz)

print(type(matriz))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [11]:
# Criar um array como um tipo específico:

# Criar um matriz com o tipo Float:

mtFloat = np.array([1,2,3], dtype = np.float64)

print(mtFloat)

print(type(mtFloat))

# Criar uma matriz com o tipo Inteiro:

mtInteiro = np.array([4,5,6,7,8], dtype = np.int32)

print(mtInteiro)

print(type(mtInteiro))


[1. 2. 3.]
<class 'numpy.ndarray'>
[4 5 6 7 8]
<class 'numpy.ndarray'>


In [14]:
# Mudar o tipo do array :
# Podemos transformar tipos de dados de arrays :

mtnew = np.array([450.66,555.54,554.5])

print(mtnew)

# Transformando de float para Int :

mtnewint = mtnew.astype(np.int32)

print(mtnewint)


[450.66 555.54 554.5 ]
[450 555 554]


In [24]:
# Transformando de Int para Float :

mtInteiro = np.array([1,5,8,9,10,50])

print(mtInteiro)

mtnewInteiro = mtInteiro.astype(np.float64)

print(mtnewInteiro)

[ 1  5  8  9 10 50]
[ 1.  5.  8.  9. 10. 50.]


In [30]:
# Mais de uma dimensão:
# Criando uma matriz bidimensional:

mtBidimensional = np.array([[1,5,2,45],[3,5,8,6],[1,512,665,56]])

print(mtBidimensional)


[[  1   5   2  45]
 [  3   5   8   6]
 [  1 512 665  56]]


In [48]:
# Cria arrays vazios tipificados :

# empty significa que não são inicializados, não que estão vazios

vazio = np.empty([5,3], dtype = np.float64 )
print(vazio)

# Criar uma matriz 4x3 com valores 0 :
print('-----------------')
zeros = np.zeros([4,3])
print(zeros)

# Criar uma matriz com valores iguais a 1 :
print('-----------------')
um = np.ones([5,7])
print(um)

# Cria uma matriz quadrada com diagonal principal com valores 1 e os outros valores 0 :
print('-----------------')
diagonal = np.eye(5)
print(diagonal)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-----------------
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [12]:
# Importando o numpy :
import numpy as np
# Valores aleatórios entre 0 e 1 :
aleatorio = np.random.random((5))
print(aleatorio)

print("--------")
# Números aleatórios negativos : 
aleatorio2 = np.random.randn((5))
print(aleatorio2)

print("-----------")
# Números aleatórios até 10 :
aleatorio3 = (10*np.random.random((4,3)))
print(aleatorio10)


[0.37596968 0.45964744 0.64792243 0.42199236 0.13310667]
--------
[-0.39540992 -0.34142748 -0.24944277 -0.45491007  3.43749001]
-----------
[[93.90669377 45.25897507  9.68939184]
 [27.76258579 24.67894368 40.58968795]
 [97.99097486 54.69438184 40.4080555 ]
 [92.47573812 22.23822953 41.43951727]]


In [44]:
# Outra forma de gerar aleatórios 
# Uso de semente :
# Com a semente, os números aleatórios seram os mesmos 
semente = np.random.default_rng(1) # Se eu colocar semente como (2) os números mudam
aleatorio4 = semente.random((3))
print(aleatorio4)

# Gerar inteiros :
print("-------")
aleatorio5 = semente.integers(10, size=(3,4))
print(aleatorio5)


[0.51182162 0.9504637  0.14415961]
-------
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [53]:
# Unique remove repetições :

repeticoes = np.array([1,2,5,9,6,3,2,1,5,3,5,2,1])
repeticoes = np.unique(repeticoes)

print(repeticoes)

[1 2 3 5 6 9]
<class 'numpy.ndarray'>


In [63]:
# Funções específicas :
# Criar uma matriz bidimensional :

bidimensional = np.array([[0,25,20,20],[546,5,14,2],[58,85,55,66]])
# Mostrar a matriz :
print(bidimensional)

# Mostrar um elemento específico da matriz :
print(bidimensional[1][0])

# Mostrar o tamanho das dimensões da matriz :
print(bidimensional.shape)


[[  0  25  20  20]
 [546   5  14   2]
 [ 58  85  55  66]]
546
(3, 4)


In [72]:
# Funções Matematicas :

# Mostra o maior valor da matriz bidimensional :
print(bidimensional.max())

# Mostra o menor valor da matriz bidimensional :
print(bidimensional.min())

# Mostra a soma dos valores da matriz bidimensional :
print(bidimensional.sum())

# Mostra o valor da média dos valores da matriz bidimensional :
print(bidimensional.mean())

# Mostra o valor do desvio padrão (Standart Deviation )dos valores da matriz bidimensional :
print(bidimensional.std())

546
0
896
74.66666666666667
144.57831403391344


In [79]:
# Funções universais aplicadas a todos os elementos :
# Mostra o valor das raiz quadrada de todos os elementos :

raizQuadrada = np.array([1,4,9])
print(np.sqrt(raizQuadrada))

# Mostrar o valor do exponencial de todos os elementos :
print(np.exp(raizQuadrada))


[1. 2. 3.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]


In [85]:
# Extração de elementos :
m = np.array([5,9,8,360,5])
print(m)

# Mostrar o elemento da posição 2 :
print(m[1])

# Mostrar os elemntos a partir da posição 0 a 2 :
print(m[0:2])

# Mostrar a partir da 2 posição até o restante do array :
print(m[1:])

# Mostrar o array criado a partir da antrepenultima posição até o final :

print(m[-3:])
# A última posição é -1 a penultima é -2 e a antepenultima é -3

[  5   9   8 360   5]
9
[5 9]
[  9   8 360   5]
[  8 360   5]


In [96]:
# Extração de linhas e colunas :
i = np.array([[7,4],[8,5],[9,1]])
print(i)
print("-----------------------------")
# Primeira linha de todas as colunas :
linha_um = i[0,:]
print(linha_um)
print("----------------------------")

# Segunda linha 
linha_dois = i[1, :]
print(linha_dois)
print("----------------------------")
# Terceira linha :
linha_tres = i[2, :]
print(linha_tres)
print("----------------------------")
# Todas as linhas primeiro coluna :
primeiraColuna = i[:,0]
print(primeiraColuna)
print("----------------------------")

# Todas as linhas segunda coluna :
segundaColuna = i[:,1]
print(segundaColuna)

[[7 4]
 [8 5]
 [9 1]]
-----------------------------
[7 4]
----------------------------
[8 5]
----------------------------
[9 1]
----------------------------
[7 8 9]
----------------------------
[4 5 1]
----------------------------


In [108]:
# Operações matematicas com matrizes :
p = np.array([[1,2],[3,4]])
m = np.array([[1,2],[3,4]])
print(p,m)
print("------------")
adicao = p + m
print(adicao)
print("------------")
multiplicacao = p * m
print(multiplicacao)
print("------------")

divisao = p / m
print(divisao)
print("------------")

subtracao = p - m
print(subtracao)
print("------------")

# Outra forma :
print(p+m)
print("------------")
print(p*m)
print("------------")
print(p/m)
print("------------")
print(p-m)


[[1 2]
 [3 4]] [[1 2]
 [3 4]]
------------
[[2 4]
 [6 8]]
------------
[[ 1  4]
 [ 9 16]]
------------
[[1. 1.]
 [1. 1.]]
------------
[[0 0]
 [0 0]]
------------
[[2 4]
 [6 8]]
------------
[[ 1  4]
 [ 9 16]]
------------
[[1. 1.]
 [1. 1.]]
------------
[[0 0]
 [0 0]]


In [114]:
# Transposição rearranja um conjunto de 15 elementos  de 0 a 14 em 3 linhas e 5 colunas :
f = np.arange(15).reshape((3,5))
print(f)
print("-----------------")
# Mostra a matriz transpostas entre linhas e colunas :
s = f.T
print(s)




[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [116]:
# Outra forma de fazer a mesma coisa :
g = np.arange(15).reshape((3,5))
print(g)
print("-----------------------")

# Mostra a matriz transpostas entre linhas e colunas :
v = g.transpose(1,0)
print(v)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [122]:
# Expressões lógicas :
# Usando where :
# Criando matriz com valores aleatórios positivos e negativos :
w = np.random.randn(4,4)
print(w)
print("----------------------")

# Criando matriz com valores booleanos baseados no array w :

x = (w > 0 )
print(x)
print("----------------------")


# Criando matriz com valores -1 e 1 baseados nos valores do array w
z = np.where(x > 0,1, -1)
print(z)


[[ 1.0018424   1.82664008 -0.65939605 -0.26891481]
 [-0.83654664  0.80263173  0.34692365 -0.03573106]
 [ 1.39694796 -1.4192606   0.03269418  1.10698249]
 [ 0.94070228  1.13194391  1.21044696  0.38376149]]
----------------------
[[ True  True False False]
 [False  True  True False]
 [ True False  True  True]
 [ True  True  True  True]]
----------------------
[[ 1  1 -1 -1]
 [-1  1  1 -1]
 [ 1 -1  1  1]
 [ 1  1  1  1]]
