**Numpy:**

In [1]:
# Importanto o numpy :

import numpy as np

# Criar uma matriz unidimensional:

matriz = np.array([1,2,3,4,5,6])

print(matriz)

print(type(matriz))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [11]:
# Criar um array como um tipo específico:

# Criar um matriz com o tipo Float:

mtFloat = np.array([1,2,3], dtype = np.float64)

print(mtFloat)

print(type(mtFloat))

# Criar uma matriz com o tipo Inteiro:

mtInteiro = np.array([4,5,6,7,8], dtype = np.int32)

print(mtInteiro)

print(type(mtInteiro))


[1. 2. 3.]
<class 'numpy.ndarray'>
[4 5 6 7 8]
<class 'numpy.ndarray'>


In [14]:
# Mudar o tipo do array :
# Podemos transformar tipos de dados de arrays :

mtnew = np.array([450.66,555.54,554.5])

print(mtnew)

# Transformando de float para Int :

mtnewint = mtnew.astype(np.int32)

print(mtnewint)


[450.66 555.54 554.5 ]
[450 555 554]


In [24]:
# Transformando de Int para Float :

mtInteiro = np.array([1,5,8,9,10,50])

print(mtInteiro)

mtnewInteiro = mtInteiro.astype(np.float64)

print(mtnewInteiro)

[ 1  5  8  9 10 50]
[ 1.  5.  8.  9. 10. 50.]


In [30]:
# Mais de uma dimensão:
# Criando uma matriz bidimensional:

mtBidimensional = np.array([[1,5,2,45],[3,5,8,6],[1,512,665,56]])

print(mtBidimensional)


[[  1   5   2  45]
 [  3   5   8   6]
 [  1 512 665  56]]


In [48]:
# Cria arrays vazios tipificados :

# empty significa que não são inicializados, não que estão vazios

vazio = np.empty([5,3], dtype = np.float64 )
print(vazio)

# Criar uma matriz 4x3 com valores 0 :
print('-----------------')
zeros = np.zeros([4,3])
print(zeros)

# Criar uma matriz com valores iguais a 1 :
print('-----------------')
um = np.ones([5,7])
print(um)

# Cria uma matriz quadrada com diagonal principal com valores 1 e os outros valores 0 :
print('-----------------')
diagonal = np.eye(5)
print(diagonal)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-----------------
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
